/* Generated by AN DISI Unibo */ 
package it.unibo.blinking

import it.unibo.kactor.*
import alice.tuprolog.*
import kotlinx.coroutines.CoroutineScope
import kotlinx.coroutines.delay
import kotlinx.coroutines.launch
import kotlinx.coroutines.runBlocking
	
class Blinking ( name: String, scope: CoroutineScope ) : ActorBasicFsm( name, scope){
 	
	override fun getInitialState() : String{
		return "s0"
	}
		
	override fun getBody() : (ActorBasicFsm.() -> Unit){
		return { //this:ActionBasciFsm
				state("s0") { //this:State
					action { //it:State
					}
					 transition( edgeName="goto",targetState="sendBlinkingMsg", cond=doswitch() )
				}	 
				state("sendBlinkingMsg") { //this:State
					action { //it:State
						itunibo.robot.robotSupport.move( "msg(${payloadArg(0)})"  )
						delay(500) 
					}
					 transition( edgeName="goto",targetState="sendBlinkingMsg", cond=doswitch() )
				}	 
			}
		}
}
